# 1. This list is used by NimbroNetwork for mutual communication of the UAVs
#    The names of the robots have to match hostnames described in /etc/hosts.
#
# 2. This list is used by MpcTracker for mutual collision avoidance of the UAVs.
#    The names should match the true "UAV_NAMES" (the topic prefixes).
#
#     network_config:=~/config/network_config.yaml
#
#    to the core.launch and nimbro.launch.

network:

  robot_names: [

    uav1,
    uav2,
    uav3,
    uav4,
    uav5,
    uav6,
    uav7,
    uav8,
    uav9,
    uav10,
    uav11,
    uav12,
    uav13,
    uav14,
    uav15,
    uav16,
    uav17,
    uav18,
    uav19,
    uav20,
    uav21,
    uav22,
    uav23,
    uav24,
    uav25,
    uav26,
    uav27,
    uav28,
    uav29,
    uav30,
    # uav31,
    # uav32,
    # uav33,
    # uav34,
    # uav35,
    # uav36,
    # uav37,
    # uav38,
    # uav39,
    # uav40,
    # uav41,
    # uav42,
    # uav43,
    # uav44,
    # uav45,
    # uav46,
    # uav47,
    # uav48,
    # uav49,
    # uav50,


  ]
